param (
    [Parameter(Mandatory=$true)]
    [string]
    $EmailAddress,

    [Parameter(Mandatory=$true)]
    [string]
    $AdminUsername,

    [Boolean]
    $BlockDomain = $false,

    [Boolean]
    $BlockSender = $true,

    [int32]
    $DayRange = 14,

    [string]
    $HostedContentFilterPolicy # NSMSpam
)
# ---------------------------------------- Block any more emails from coming in
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -UserPrincipalName $AdminUsername



if ($BlockSender -eq $true) {
    if ($null -ne (Get-HostedContentFilterPolicy -Identity $HostedContentFilterPolicy)) {
        Write-Host "Adding $EmailAddress to blocked senders list"
        Set-HostedContentFilterPolicy -Identity $HostedContentFilterPolicy -BlockedSenders @{Add="$EmailAddress"}
    } else {
        Write-Error "Hosted content filter policy '$HostedContentFilterPolicy' not found"
    }
}

if ($BlockDomain -eq $true) {
    $Domain = ($EmailAddress).split('@')[1]
    if ($null -ne (Get-HostedContentFilterPolicy -Identity $HostedContentFilterPolicy)) {
        Write-Host "Adding $Domain to blocked domains list"
        Set-HostedContentFilterPolicy -Identity $HostedContentFilterPolicy -BlockedSenderDomains @{Add="$Domain"}
    } else {
        Write-Error "Hosted content filter policy '$HostedContentFilterPolicy' not found"
    }
}

# ---------------------------------------- Purge existing emails out there
Connect-IPPSSession -UserPrincipalName $AdminUsername

$ComplianceSearchName = "SuspiciousEmail_$EmailAddress"
$DateRangeBegin = (Get-Date).AddDays(-$DayRange) | Get-Date -Format yyyy-MM-dd
$DateRangeEnd = (Get-Date).AddDays(0) | Get-Date -Format yyyy-MM-dd

# Search the past $DayRange days
Write-Host "Creating compliance/content search with name '$ComplianceSearchName' for the past $DayRange days"
New-ComplianceSearch -Name $ComplianceSearchName -ExchangeLocation All -Description "Compliance search generated by script authored by Witt Allen" `
-ContentMatchQuery "(c:c)(senderauthor=$EmailAddress)(received=$DateRangeBegin..$DateRangeEnd)"
Start-ComplianceSearch -Identity $ComplianceSearchName

while ((Get-ComplianceSearch $ComplianceSearchName).Status -ne "Completed") {
    Write-Host "$(Get-Date -Format hh:mm) - Search not yet complete"
    Start-Sleep -Seconds (60*1)
}
Write-Host "$(Get-Date -Format hh:mm) - Search complete!"

# Purge the search results from mailboxes
New-ComplianceSearchAction -SearchName $ComplianceSearchName -Purge -PurgeType HardDelete -Confirm:$false
# Notify when purge is complete
while ((Get-ComplianceSearchAction | Where-Object {($_.SearchName -match $ComplianceSearchName) -and ($_.Action -match "Purge")}).Status -ne "Completed") {
    Write-Host "$(Get-Date -Format hh:mm) - Purge not yet complete"
    Start-Sleep -Seconds (60*1)
}
$SearchAction = Get-ComplianceSearchAction | Where-Object {($_.SearchName -match $ComplianceSearchName) -and ($_.Action -match "Purge")}
Write-Host "$(Get-Date -Format hh:mm) - Purge complete!`nResults: $($SearchAction.Results)`n`nJob well done! Cheers!"